Repository amzn/pecos, pull requests merged in 2021-05, with the labels that each got.

#13 recast variable type in c++ to avoid overflow
  pecos/core/utils/matrix.hpp
  pecos/core/xmc/linear_solver.hpp
Labels: enhancement

#12 Add Makefile for easy format, install, clean and unittest
  .github/style_type_check_cfg/.black
  .github/style_type_check_cfg/.flake8
  .github/style_type_check_cfg/.mypy
  .github/workflows/style_type_check.yml
  .style_type.cfg
  CONTRIBUTING.md
  Makefile
Labels: documentation, enhancement

#14 Fix transformer training issue on single GPU
  pecos/xmc/xtransformer/matcher.py
  pecos/xmc/xtransformer/network.py
  test/pecos/xmc/xtransformer/test_xtransformer.py
Labels: bug

#16 Single-source style/type/unittest in GitActions
  .github/workflows/pytest.yml
  .github/workflows/style_type_check.yml
Labels: enhancement

#20 avoid ensemble for text2text prediction with sinlge model
  pecos/apps/text2text/model.py
Labels: enhancement

#21 Improve error message for installation in non-git repo
  setup.py
Labels: enhancement
